{-# LANGUAGE CPP #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif
{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintLambdaNat.
--   Generated by the BNF converter.

module PrintLambdaNat where

import qualified AbsLambdaNat
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else ' ':s)

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsLambdaNat.Id where
  prt _ (AbsLambdaNat.Id i) = doc (showString i)

instance Print AbsLambdaNat.Program where
  prt i e = case e of
    AbsLambdaNat.Prog exp -> prPrec i 0 (concatD [prt 0 exp])

instance Print AbsLambdaNat.Exp where
  prt i e = case e of
    AbsLambdaNat.EAbs id exp -> prPrec i 1 (concatD [doc (showString "\\"), prt 0 id, doc (showString "."), prt 0 exp])
    AbsLambdaNat.EIf exp1 exp2 exp3 exp4 -> prPrec i 2 (concatD [doc (showString "if"), prt 0 exp1, doc (showString "="), prt 0 exp2, doc (showString "then"), prt 0 exp3, doc (showString "else"), prt 0 exp4])
    AbsLambdaNat.ELet id exp1 exp2 -> prPrec i 3 (concatD [doc (showString "let"), prt 0 id, doc (showString "="), prt 0 exp1, doc (showString "in"), prt 0 exp2])
    AbsLambdaNat.ERec id exp1 exp2 -> prPrec i 4 (concatD [doc (showString "let"), doc (showString "rec"), prt 0 id, doc (showString "="), prt 0 exp1, doc (showString "in"), prt 0 exp2])
    AbsLambdaNat.EHd exp -> prPrec i 6 (concatD [doc (showString "hd"), prt 0 exp])
    AbsLambdaNat.ETl exp -> prPrec i 6 (concatD [doc (showString "tl"), prt 0 exp])
    AbsLambdaNat.EMinusOne exp -> prPrec i 7 (concatD [doc (showString "minus_one"), prt 0 exp])
    AbsLambdaNat.EApp exp1 exp2 -> prPrec i 8 (concatD [prt 8 exp1, prt 9 exp2])
    AbsLambdaNat.ENil -> prPrec i 9 (concatD [doc (showString "#")])
    AbsLambdaNat.ECons exp1 exp2 -> prPrec i 9 (concatD [prt 10 exp1, doc (showString ":"), prt 9 exp2])
    AbsLambdaNat.ENat0 -> prPrec i 10 (concatD [doc (showString "0")])
    AbsLambdaNat.ENatS exp -> prPrec i 10 (concatD [doc (showString "S"), prt 10 exp])
    AbsLambdaNat.EVar id -> prPrec i 11 (concatD [prt 0 id])
    AbsLambdaNat.EFix exp -> prPrec i 5 (concatD [doc (showString "fix"), prt 0 exp])

