-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

module AbsLambda where

newtype Id = Id String
  deriving (Eq, Ord, Show, Read)

data Exp = EAbs Id Exp | EApp Exp Exp | EVar Id
  deriving (Eq, Ord, Show, Read)

